### ISSUE TITLE
Validation errors on COVID-19 Note HTML Entry form

### ISSUE THREAD

**Issue by bmamlin** [openmrs-indianaems/openmrs-indianaems-config#1]
When saving the COVID-19 HTML Form Entry form, there are validation errors reading "The answer concept specified is not a valid concept for this question concept," suggesting there will be errors collecting data with the form.

![image](https://user-images.githubusercontent.com/860834/78559820-0d248480-77e3-11ea-9f93-a4c65c9cfbb0.png)

**Comment by jamlung-ri** [comment]
I am planning to check on this one. What I don't know is the consequence of this issue. What happens if we try to save an answer to a question concept that does not expect it?

**Comment by bmamlin** [comment]
If there's a coded question with a set of possible answers and our form stores a answer code that is _not_ in that list, then it wouldn't be a technically valid answer for the concept, but likely wouldn't throw an error while the form is being filled. If we have cases where datatypes don't match (e.g., a numeric concept answered with a concept or a coded concept answered with a number or string), then it could create errors during usage and more problems down the road.

**Comment by jamlung-ri** [comment]
This has been fixed by making sure that all answer concepts are part of the question concepts. This either involved adding answers to a locally-created question or by changing the question concept to which an answer was mapped. These changes are all noted in [our COVID Data Dictionary](https://docs.google.com/spreadsheets/d/1fvp8uUJ8IbZ8oSrgecYM8k6wckTpBu1WlpnqVewiM88/).
