### ISSUE TITLE
COVID FORM - Symptoms loss of smell and taste

### ISSUE THREAD

**Issue by jburnsthomas** [openmrs-indianaems/openmrs-indianaems-config#23]
COVID FORM - Current symptoms - Loss of sense of smell and loss of sense of taste

**Comment by jamlung-ri** [comment]
I have updated the COVID form in the Dev environment and the GitHub repo. I have also added concepts to the Initializer CSV files, which are now up to date in GitHub. Unless otherwise instructed, I do not plan to make any changes into the Test environment. Leaving this ticket open until that is done.

**Comment by jburnsthomas** [comment]
@bmamlin and @maurya can this changesbe made in the test environment? Or is there another next step.

**Comment by maurya** [comment]
@jamlung-ri , I updated the test environment with your changes, please test and let us know if anything is not functioning - http://indianaems2.openmrs.org

**Comment by jamlung-ri** [comment]
This is now working properly.
